[package]
name = "serde-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.37", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
